### ISSUE TITLE
Pass the data to each worker

### ISSUE THREAD

**Issue by vbakayov** [phenology/platform-for-pheno-products#4]
The dataset should be made available to each machine. 

Try to find a solution to pipe the data from HDFS and directly access it from there.

A possibly solution is to copy the data over each of the machines and access it locally.

**Comment by romulogoncalves** [comment]
Spark is designed to work with different types of data storage. When downloading data from the web we should not directly store in HDFS. HDFS is where the intermediates and prepared data should exist for processing. Large data banks of data, in this case remote sensing data, should be hosted in a different storage. 

Imagine we were running at Amazon, all NetCDF files downloaded would be stored at Amazon S3. Amazon S3 will be your data bank. From there you would download/stream the files and convert them, pre-process them and make them available for Spark processing. The conversion and pre-processing could take advantage of Spark to distribute the work and the results uploaded to HDFS in a Spark friendly format so it is then efficiently loaded as a DataFrame for data analysis.

In our local setup we could save the files to Minio which has a S3 interface. The data conversion, in a Map function, will simply download the files locality, save them into Minio. Then you would access them from Minio, a shared storage, and pre-process them with TimeSat. The result could be put back in Minio (you can access it directly from Spark) or in HDFS as a Parquet file using Apache Arrow (PyArrow allows to do it from Python). The parquet files could them be merged into a DataFrame in Spark for further processing. 

With this solution you are ready to handle large data sets and your solution could easily be ported to commercial cloud providers since all provide S3 interface. Solution portability to different platforms, something important in a BigData solution.

**Comment by romulogoncalves** [comment]
To mount a S3/minio remote bucket, https://github.com/minio/minfs has information (Note: they recommend to use rexray/s3fs and goofys.

**Comment by vbakayov** [comment]
The goofys integration was mounted on each of the machines. 

However, I believe as data is not physically present, it requires some time to fetch from remote. As the TimeSat library does not block to wait for the complete download, it results in an error.

Not sure if issue is due to Minio or the goofys or it is something else, Downloading files from the Minio Web UI also can result in  incomplete damaged files, strange  

Solution might be a disk cache : https://github.com/kahing/catfs . This software is in ALPHA stage :(

**Comment by vbakayov** [comment]
goofys experienced problems with incomplete files due to network connection resets. This would corrupt the files and render them unusable. We moved to s3fs.
No local disk cache is present, currently. We might need to explore options to cache the files if there are repetitive uses of the same files. However, no sync to the cache is present, and might fill up space quickly as files would not be deleted if they are deleted in Minio. A job would need to be created to periodically clean the directory

The installation was as follows (prerequisite install the 'fuse' library)
git clone https://github.com/s3fs-fuse/s3fs-fuse.git
cd s3fs-fuse
./autogen.sh
./configure
make
sudo make install

The configuration was : 
echo   minio_access_key:minio_secret_key  ~/.s3cred
chmod 600  ~/.s3cred
sudo mkdir /data/local/home/parrot/minio6

Starting is: 
sudo s3fs datastorage /data/local/home/parrot/minio6 -o uid=0,umask=0000,gid=0 -o allow_other -o passwd_file=~/.s3cred,use_path_request_style,allow_other,url=http://parrot0.phenovari-utwente.surf-hosted.nl:9091

Nice feature to have :
Ansible can start the fuse after network and minio server is up:
